POST http://localhost:5000/store-in-db
Content-Type: application/json

{
    "username" : "Akshay",
    "age" : 18,
    "email" : "akkiakshay440@gmail.com",
    "location" : "Warangal"
}

###

POST https://micro-service-a.onrender.com/user-details
Content-Type: application/json

{
    "username" : "Akshay",
    "age" : 18,
    "email" : "akkiakshay440@gmail.com",
    "location" : "Warangal"
}

###

POST https://micro-service-b.onrender.com/store-in-db
Content-Type: application/json

{
    "username" : "Akshay",
    "age" : 18,
    "email" : "akkiakshay440@gmail.com",
    "location" : "Warangal"
}
